spring:
  security:
    oauth:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9090"
      client:
        registration:
          client-app:
            provider: spring
            client-id: sofia
            client-secret: sofia2020
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope:
              -openid
              -profile
              -read
            client-name: client-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9090"